[package]
name = "configuer"
version = "0.1.0"
authors = ["Milesq <wmilosz88@gmail.com>"]
edition = "2018"

[features]
default = ["dirs"]

[dependencies]
dirs = { version = "3.0.1", optional = true }
serde = { version = "1.0.114", features = ["derive"] }
bincode = "1.3.1"
